/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.WeatherAppModel;
import java.util.LinkedList; // Use java.util.List
import java.util.List; // Correct import for List
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Acer
 */
public class DetailHomepage extends javax.swing.JFrame {
    private final List<WeatherAppModel> weatherdataList = new LinkedList<>(); // List to hold weather data
    private final DefaultTableModel weatherTableModel;

    /**
     * Creates new form UpdatedHomepage
     */
    public DetailHomepage() {
        // Initialize the table model
        weatherTableModel = (DefaultTableModel) tblWeatherTable.getWeatherAppModel();
        // Load sample data into the table
        loadSampleData();
    }

    // Method to load sample data into the weather list and table
    private void loadSampleData() {
        // Sample data
        weatherdataList.add(new WeatherAppModel(1, "Sunny", 30, 60, 10, 1013)); // Example data
        weatherdataList.add(new WeatherAppModel(2, "Rainy", 25, 80, 5, 1008));
        weatherdataList.add(new WeatherAppModel(3, "Cloudy", 20, 70, 15, 1010));
        weatherdataList.add(new WeatherAppModel(4, "Windy", 22, 50, 20, 1005));
        weatherdataList.add(new WeatherAppModel(5, "Stormy", 18, 90, 25, 995));

        // Update the table model with the sample data
        for (WeatherAppModel weather : weatherdataList) {
            weatherTableModel.addRow(new Object[]{
                weather.getTemperature(),
                weather.getHumidity(),
                weather.getVisibility(),
                weather.getPressure(),
                weather.getWindSpeed()
            });
        }
    }

    // Other methods (initializeLayout, startProgress, etc.) should be defined here
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbbackground = new javax.swing.JPanel();
        jlbkathmandu = new javax.swing.JLabel();
        jblhome = new javax.swing.JButton();
        jsptable = new javax.swing.JScrollPane();
        tblWeatherTable = new javax.swing.JTable();
        jbAboutus = new javax.swing.JButton();
        jbldetailbackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbbackground.setMaximumSize(new java.awt.Dimension(1000, 700));
        jlbbackground.setMinimumSize(new java.awt.Dimension(1000, 700));
        jlbbackground.setPreferredSize(new java.awt.Dimension(1000, 700));
        jlbbackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbkathmandu.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlbkathmandu.setForeground(new java.awt.Color(255, 255, 255));
        jlbkathmandu.setText("Kathmandu");
        jlbbackground.add(jlbkathmandu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jblhome.setText("Home");
        jlbbackground.add(jblhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        tblWeatherTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Temperature", "Humidity", "Visibility", "Pressure", "WindSpeed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jsptable.setViewportView(tblWeatherTable);

        jlbbackground.add(jsptable, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 510, 280));

        jbAboutus.setText("About us");
        jlbbackground.add(jbAboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        jbldetailbackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sky blue.jpg"))); // NOI18N
        jbldetailbackground.setText("jLabel1");
        jbldetailbackground.setMaximumSize(new java.awt.Dimension(1000, 700));
        jbldetailbackground.setMinimumSize(new java.awt.Dimension(1000, 700));
        jbldetailbackground.setPreferredSize(new java.awt.Dimension(1000, 700));
        jlbbackground.add(jbldetailbackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -200, 1040, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlbbackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlbbackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailHomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAboutus;
    private javax.swing.JLabel jbldetailbackground;
    private javax.swing.JButton jblhome;
    private javax.swing.JPanel jlbbackground;
    private javax.swing.JLabel jlbkathmandu;
    private javax.swing.JScrollPane jsptable;
    private javax.swing.JTable tblWeatherTable;
    // End of variables declaration//GEN-END:variables
}
