
package View;

/**
 *
 * @author Acer
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbbackground = new javax.swing.JPanel();
        jlbkathmandu = new javax.swing.JLabel();
        jblhome = new javax.swing.JButton();
        jblweatherdetail = new javax.swing.JButton();
        jsptable2 = new javax.swing.JScrollPane();
        tblWeatherTable2 = new javax.swing.JTable();
        jbAboutus = new javax.swing.JButton();
        jplsecondbackgroung = new javax.swing.JPanel();
        jlbtemp = new javax.swing.JLabel();
        jlbhumidity = new javax.swing.JLabel();
        jlbvisibility = new javax.swing.JLabel();
        jlbpressure = new javax.swing.JLabel();
        jlbWindSpeed = new javax.swing.JLabel();
        txtwindspeed = new javax.swing.JTextField();
        txttemp = new javax.swing.JTextField();
        txthumidity = new javax.swing.JTextField();
        txtvisibility = new javax.swing.JTextField();
        txtpressure1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbadd = new javax.swing.JButton();
        jbdelete = new javax.swing.JButton();
        jbclearall = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));

        jlbbackground.setMaximumSize(new java.awt.Dimension(1000, 700));
        jlbbackground.setMinimumSize(new java.awt.Dimension(1000, 700));
        jlbbackground.setPreferredSize(new java.awt.Dimension(1000, 700));
        jlbbackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbkathmandu.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jlbkathmandu.setForeground(new java.awt.Color(255, 255, 255));
        jlbkathmandu.setText("Kathmandu");
        jlbbackground.add(jlbkathmandu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jblhome.setText("Home");
        jlbbackground.add(jblhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jblweatherdetail.setText("Weather Detail");
        jlbbackground.add(jblweatherdetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        tblWeatherTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Temperature", "Humidity", "Visibility", "Pressure", "WindSpeed"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jsptable2.setViewportView(tblWeatherTable2);

        jlbbackground.add(jsptable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 600, 280));

        jbAboutus.setText("About us");
        jlbbackground.add(jbAboutus, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, -1, -1));

        jplsecondbackgroung.setBackground(new java.awt.Color(204, 204, 255));
        jplsecondbackgroung.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbtemp.setText("Temperature");
        jplsecondbackgroung.add(jlbtemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jlbhumidity.setText("Humidity");
        jplsecondbackgroung.add(jlbhumidity, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jlbvisibility.setText("Visibility");
        jplsecondbackgroung.add(jlbvisibility, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jlbpressure.setText("Pressure");
        jplsecondbackgroung.add(jlbpressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jlbWindSpeed.setText("WindSpeed");
        jplsecondbackgroung.add(jlbWindSpeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));
        jplsecondbackgroung.add(txtwindspeed, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 120, -1));
        jplsecondbackgroung.add(txttemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 120, -1));
        jplsecondbackgroung.add(txthumidity, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 120, -1));
        jplsecondbackgroung.add(txtvisibility, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 120, -1));
        jplsecondbackgroung.add(txtpressure1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 120, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jplsecondbackgroung.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, 290));

        jbadd.setText("ADD");
        jbadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbaddActionPerformed(evt);
            }
        });
        jplsecondbackgroung.add(jbadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 150, 40));

        jbdelete.setText("Delete");
        jbdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdeleteActionPerformed(evt);
            }
        });
        jplsecondbackgroung.add(jbdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 150, 40));

        jbclearall.setText("Clear All");
        jbclearall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbclearallActionPerformed(evt);
            }
        });
        jplsecondbackgroung.add(jbclearall, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 150, 40));

        jlbbackground.add(jplsecondbackgroung, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 600, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sky blue.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1000, 700));
        jLabel1.setMinimumSize(new java.awt.Dimension(1000, 700));
        jLabel1.setPreferredSize(new java.awt.Dimension(1000, 700));
        jlbbackground.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-280, 60, 1040, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlbbackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlbbackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdeleteActionPerformed
        // TODO add your handling code here:
                                        
    // Get the selected row index
    int selectedRow = tblWeatherTable2.getSelectedRow();

    // Check if a row is selected
    if (selectedRow != -1) {
        // Get the table model
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblWeatherTable2.getModel();
        
        // Remove the selected row
        model.removeRow(selectedRow);
        javax.swing.JOptionPane.showMessageDialog(this, "Deleted succesfull!!!.", "Selection Error", javax.swing.JOptionPane.WARNING_MESSAGE);
    } else {
        // Show a message if no row is selected
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a row to delete.", "Selection Error", javax.swing.JOptionPane.WARNING_MESSAGE);
    }

    }//GEN-LAST:event_jbdeleteActionPerformed

    private void jbaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbaddActionPerformed
        // TODO add your handling code here:                                     
    // Get the values from the text fields
    String temperature = txttemp.getText();
    String humidity = txthumidity.getText();
    String visibility = txtvisibility.getText();
    String pressure = txtpressure1.getText();
    String windSpeed = txtwindspeed.getText();

    // Validate input (you can add more validation as needed)
    if (temperature.isEmpty() || humidity.isEmpty() || visibility.isEmpty() || pressure.isEmpty() || windSpeed.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Input Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Get the table model
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblWeatherTable2.getModel();

    // Add a new row with the input data
    model.addRow(new Object[]{temperature, humidity, visibility, pressure, windSpeed});

    // Clear the text fields after adding
    txttemp.setText("");
    txthumidity.setText("");
    txtvisibility.setText("");
    txtpressure1.setText("");
    txtwindspeed.setText("");
    
    }//GEN-LAST:event_jbaddActionPerformed

    private void jbclearallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbclearallActionPerformed
        // TODO add your handling code here:
                                         
    // Clear all text fields
    txttemp.setText("");
    txthumidity.setText("");
    txtvisibility.setText("");
    txtpressure1.setText("");
    txtwindspeed.setText("");

    // Optionally, clear the table
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblWeatherTable2.getModel();
    model.setRowCount(0); // This will remove all rows from the table

    }//GEN-LAST:event_jbclearallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAboutus;
    private javax.swing.JButton jbadd;
    private javax.swing.JButton jbclearall;
    private javax.swing.JButton jbdelete;
    private javax.swing.JButton jblhome;
    private javax.swing.JButton jblweatherdetail;
    private javax.swing.JLabel jlbWindSpeed;
    private javax.swing.JPanel jlbbackground;
    private javax.swing.JLabel jlbhumidity;
    private javax.swing.JLabel jlbkathmandu;
    private javax.swing.JLabel jlbpressure;
    private javax.swing.JLabel jlbtemp;
    private javax.swing.JLabel jlbvisibility;
    private javax.swing.JPanel jplsecondbackgroung;
    private javax.swing.JScrollPane jsptable2;
    private javax.swing.JTable tblWeatherTable2;
    private javax.swing.JTextField txthumidity;
    private javax.swing.JTextField txtpressure1;
    private javax.swing.JTextField txttemp;
    private javax.swing.JTextField txtvisibility;
    private javax.swing.JTextField txtwindspeed;
    // End of variables declaration//GEN-END:variables
}
