/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Acer
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jblsignin = new javax.swing.JLabel();
        jbllogin = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        jbuttonlogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblsignin.setText("     Sign in to your account");
        jPanel3.add(jblsignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 57, 177, 24));

        jbllogin.setBackground(new java.awt.Color(0, 0, 0));
        jbllogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbllogin.setForeground(new java.awt.Color(0, 102, 255));
        jbllogin.setText("  Login");
        jPanel3.add(jbllogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 19, 99, -1));

        txtusername.setText("Username");
        jPanel3.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 116, 300, 46));

        txtpassword.setText("Password");
        jPanel3.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 174, 300, 46));

        jbuttonlogin.setBackground(new java.awt.Color(0, 51, 153));
        jbuttonlogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbuttonlogin.setForeground(new java.awt.Color(255, 255, 255));
        jbuttonlogin.setText("Login");
        jPanel3.add(jbuttonlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 300, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 470, 380));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/weather.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(1000, 700));
        jLabel2.setMinimumSize(new java.awt.Dimension(1000, 700));
        jLabel2.setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 864, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jbllogin;
    private javax.swing.JLabel jblsignin;
    private javax.swing.JButton jbuttonlogin;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
